Create training page
AlexJanow/WeightMate pull request #21
Opened 2021-08-16 13:44 UTC by AlexJanow

2021-08-16 14:21 UTC, mpagels requested changes
Hi Alex, thx for the pr. 
I'm missing a good descriptive pull request description. For example what is this pull request about, what was done here. Maybe you have a question or want to point out something you are proud of. It is then easier for the reviewer to know on which point maybe to take a lot more care in the review.
And: I saw a lot of commented code: Highly recommended: No commented code in production code. Please remove the comments before merging.

If you have any questions, please ask me here in the pr or in zoom.

2021-08-16 14:21 UTC, mpagels commented on src/pages/SingleExercise.js
> +  const [img, setImg] = useState("");
Do you use this state anywhere? If not needed, I would remove it.

2021-08-16 14:21 UTC, mpagels commented on src/components/ChartBodyweight.js
> -  console.log(items);
Very good. ;-)

2021-08-16 14:21 UTC, mpagels commented on src/components/BodyweightResultsRender.css
> +#bodyweight__input {
Why do you use an ID here?

2021-08-16 14:21 UTC, mpagels commented on src/components/BodyweightResultsRender.css
> +  color: #2e2e33;
Would recommend using some sort of color variables here. I don't know what `#2e2e33` means. Maybe something like `primary-font-color` would be good?

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingRenderExercise.js
> +  console.log(results);
A little console.log here

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingRenderExercise.js
> +  const [exercises, setExercises] = useState([]);
Do you need the state here? I don't see this used anymore in this component.

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingRenderExercise.js
> +  const results = result.suggestions;
Why do you save the value of `suggestions` into a variable named `results`. Why not `suggestions` as well?

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingRenderExercise.js
> +          <li className="training__result-li" key={index}>
Using the index as a key is not recommended. `exercise.data.id` would be a good key as well.

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingForm.js
> +  }
This little condition is doing nothing right?

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingForm.js
> +    let isMounted = true;
What is `isMounted` doing? Why do you need it?

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingForm.js
> +          value={search && search}
I think you could write `search` here instead of `search && search`. At start is just an empyt string that is inserted here.

2021-08-16 14:21 UTC, mpagels commented on src/components/TrainingForm.js
> +        <TrainingRenderExercise result={result} />
I would highly recommend putting the `map` here. It is not good readable to go to `TrainingRenderExercise`.

2021-08-17 08:44 UTC, AlexJanow commented on src/pages/SingleExercise.js
> +        {info && info.description.replace(/(<([^>]+)>)/gi, "")}
As I wrote in the comment above: For some weird reason there are openening and closing <p> tags in the description (implemented in the API), so I use this regex to get rid of it.

2021-08-17 09:30 UTC, merged